### ISSUE TITLE
mddox fails to load against UWP assembly

### ISSUE THREAD

**Issue by asklar** [loxsmoke/mddox#10]
I'm trying to document a winmd file (a UWP WinRT component) but mddox can't seem to load it:

```
> mddox TreeDumpLibrary.winmd

Error: Could not load file or assembly 'TreeDumpLibrary, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null, ContentType=WindowsRuntime'.
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String niPath, ObjectHandleOnStack retAssembly)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at System.Reflection.Assembly.LoadFile(String path)
   at MdDox.Program.Main(String[] args) in C:\Dev\mddox\src\Program.cs:line 194
```

**Comment by loxsmoke** [comment]
Try version 0.5.1 and see if it works.

**Comment by asklar** [comment]
@loxsmoke no dice, same error...

```
Error: Could not load file or assembly 'TreeDumpLibrary, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null, ContentType=WindowsRuntime'.
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String niPath, ObjectHandleOnStack retAssembly)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at MdDox.Program.Main(String[] args) in C:\Dev\mddox\src\Program.cs:line 189
```

**Comment by loxsmoke** [comment]
You tried to document WinMD which is a different format. I do not think that .net core 3.1 can load this type of the file.

**Comment by asklar** [comment]
@loxsmoke looks like this works with the code in master, just not with what's released.
Loading WinRT assemblies is supported in .netcore 3.0 preview 5 onwards, see https://github.com/Microsoft/dotnet/issues/590

**Comment by loxsmoke** [comment]
That is weird. Must be something with tooling.
