### ISSUE TITLE
Error while read custom package

### ISSUE THREAD

**Issue by ZhivovOleg** [loxsmoke/mddox#23]
```bash
PS D:\Git\_Bars\OBP.Core.Attributes> mddox .\bin\Release\netstandard2.0\OBP.Core.Attributes.dll -o TestAutoDoc.md -f github -s latest -n
Error: Unable to load one or more of the requested types.
Could not load file or assembly 'OBP.Core.Types.Annotations, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. Не удается найти указанный файл.
Could not load file or assembly 'OBP.Core.Types.Annotations, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. Не удается найти указанный файл.
Could not load file or assembly 'OBP.Core.Types.Annotations, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. Не удается найти указанный файл.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at System.Reflection.Assembly.GetTypes()
   at LoxSmoke.DocXml.Reflection.TypeCollection.GetReferencedTypes(Assembly assembly, ReflectionSettings settings)
   at LoxSmoke.DocXml.Reflection.TypeCollection.ForReferencedTypes(Assembly assembly, ReflectionSettings settings)
   at MdDox.OrderedTypeList.LoadTypes(Type rootType, Assembly assembly, Boolean recursiveAssemblyTraversal, List`1 recursiveAssemblies, List`1 ignoreAttributes, Boolean ignoreMethods, Boolean verbose) in C:\dev\mddox\src\OrderedTypeList.cs:line 66
   at MdDox.Program.Main(String[] args) in C:\dev\mddox\src\Program.cs:line 126
```
my code works with my own (non-public) nuget lib ```OBP.Core.Types.Annotations```. 
mddox crashes on it

**Comment by loxsmoke** [comment]
Error message just says that mddox cannot load the assembly of the type. You can try run mddox from the folder where OBP.Core.Types.Annotations assembly is. See if that helps.

You can also run mddox with -v flag. It would not solve the problem but it may show some output useful for troubleshooting.
