### ISSUE TITLE
Could not load file or assembly 'netstandard, Version=2.1.0.0, ...

### ISSUE THREAD

**Issue by bert2** [loxsmoke/mddox#5]
I can't get mddox to generate markdown from my XML docs.

I installed it as a global tool and run it inside my project directory, but when I feed it my assembly it crashes with the following error:

> D:\DEV\dtmf-detection\src\DtmfDetection.NAudio
❯ mddox .\bin\Debug\netstandard2.1\DtmfDetection.NAudio.dll
Error: Unable to load one or more of the requested types.
Could not load file or assembly 'netstandard, Version=2.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
Could not load file or assembly 'netstandard, Version=2.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
Could not load file or assembly 'netstandard, Version=2.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
Could not load file or assembly 'netstandard, Version=2.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
Could not load file or assembly 'netstandard, Version=2.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
Could not load file or assembly 'netstandard, Version=2.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
Could not load file or assembly 'netstandard, Version=2.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
Could not load file or assembly 'netstandard, Version=2.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
Could not load file or assembly 'netstandard, Version=2.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
Could not load file or assembly 'netstandard, Version=2.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
Could not load file or assembly 'netstandard, Version=2.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
Could not load file or assembly 'netstandard, Version=2.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at System.Reflection.Assembly.GetTypes()
   at LoxSmoke.DocXml.Reflection.TypeCollection.GetReferencedTypes(Assembly assembly, ReflectionSettings settings)
   at MdDox.DocumentationGenerator.GenerateMarkdown(Type rootType, Assembly assembly, Boolean recursiveAssemblyTraversal, List`1 recursiveAssemblies, List`1 ignoreAttributes, Boolean ignoreMethods, Boolean msdnLinks, String msdnView, Boolean showDateLine, IMarkdownWriter markdownWriter, String outputFileName) in C:\Dev\mddox\src\DocumentationGenerator.cs:line 151
   at MdDox.Program.Main(String[] args) in C:\Dev\mddox\src\Program.cs:line 208

I noticed that mddox is a netcoreapp2.1, but my library is netstandard2.1. So I cloned this repo, changed the mddox project to netcoreapp3.1, built and ran it again from the output directory:

> D:\DEV\mddox\src\bin\Debug\netcoreapp3.1
❯ dotnet .\mddox.dll ..\\..\\..\\..\\..\dtmf-detection\src\DtmfDetection.NAudio\bin\Debug\netstandard2.1\DtmfDetection.NAudio.dll
Error: Unable to load one or more of the requested types.
Could not load file or assembly 'NAudio, Version=1.10.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at System.Reflection.Assembly.GetTypes()
   at LoxSmoke.DocXml.Reflection.TypeCollection.GetReferencedTypes(Assembly assembly, ReflectionSettings settings)
   at LoxSmoke.DocXml.Reflection.TypeCollection.ForReferencedTypes(Assembly assembly, ReflectionSettings settings)
   at MdDox.DocumentationGenerator.GenerateMarkdown(Type rootType, Assembly assembly, Boolean recursiveAssemblyTraversal, List`1 recursiveAssemblies, List`1 ignoreAttributes, Boolean ignoreMethods, Boolean msdnLinks, String msdnView, Boolean showDateLine, IMarkdownWriter markdownWriter, String outputFileName) in D:\DEV\mddox\src\DocumentationGenerator.cs:line 151
   at MdDox.Program.Main(String[] args) in D:\DEV\mddox\src\Program.cs:line 208

As you can see, it still crashes, but with a slightly different exception. Now it's NAudio.dll mddox cannot find and that's from a nuget package my library is using.

Switching the project back to netcoreapp2.1 leads to the first exception where netstandard2.1 cannot be found.

So it's two problems: mddox needs to be upgraded to netcoreapp3.1 and somehow it needs to find dlls of a referenced package?

**Comment by bert2** [comment]
I just tested mddox against itself inside its build output directory (`.\mddox.exe .\DocXml.dll`) which worked perfectly fine.

**Comment by bert2** [comment]
I could get it running by:
- using netcoreapp3.1
- copying the DLL I want to document (DtmfDetection.NAudio.dll) into mddox' build output directory
- copying all referenced DLLs (DtmfDetection.dll, NAudio.dll) into mddox' build output directory
- executing it right there with `.\mddox.exe DtmfDetection.NAudio.dll`

But this is obviously not a workable solution. Is there another way for mddox to find the referenced DLLs?

**Comment by loxsmoke** [comment]
The exception is thrown by the framework reflection functions that load type info from the assembly. 
The framework clearly does not know where to load assemblies from but I have no idea yet why it is happening exactly.  

Could you create a minimal project that mddox fails to document?

**Comment by bert2** [comment]
It's actually quite easy to create a project that cannot be documented due to unresolvable references. Here are the repro-steps:

```powershell
PS> mkdir test
PS> cd test
PS> dotnet new console
PS> dotnet add package NAudio
PS> # open .\test.csproj and change <TargetFramework> to 'netcoreapp2.1'
PS> # open .\Program.cs and add property `public NAudio.Wave.IWaveIn foo;` to `Program` class
PS> dotnet build
PS> cd .\bin\Debug\netcoreapp2.1\
PS> mddox .\test.dll
Error: Could not load file or assembly 'NAudio, Version=1.10.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
   at System.Signature.GetSignature(Void* pCorSig, Int32 cCorSig, RuntimeFieldHandleInternal fieldHandle, IRuntimeMethodInfo methodHandle, RuntimeType declaringType)
   at System.Reflection.RtFieldInfo.get_FieldType()
   at LoxSmoke.DocXml.Reflection.TypeCollection.IsCompilerGenerated(FieldInfo fieldInfo)
   at LoxSmoke.DocXml.Reflection.TypeCollection.GetReferencedBy(Type type)
   at LoxSmoke.DocXml.Reflection.TypeCollection.ProcessTypeQueue()
   at MdDox.DocumentationGenerator.GenerateMarkdown(Type rootType, Assembly assembly, Boolean recursiveAssemblyTraversal, List`1 recursiveAssemblies, List`1 ignoreAttributes, Boolean ignoreMethods, Boolean msdnLinks, String msdnView, Boolean showDateLine, IMarkdownWriter markdownWriter, String outputFileName) in C:\Dev\mddox\src\DocumentationGenerator.cs:line 151
   at MdDox.Program.Main(String[] args) in C:\Dev\mddox\src\Program.cs:line 208
```

This also fails for netstandard2.0 projects. The only thing that worked for me was rebuilding mddox against netcoreapp3.1 and creating a netcoreapp3.1 test project with `<OutputType>Exe</OutputType>`. Since netcoreapp3.1 we can create executable files again and those get all referenced assemblies copied into the output directory.

Of course mddox can always document assemblies that have no references to other assemblies.

**Comment by bert2** [comment]
My gut feeling tells me that I'm doing something entirely wrong or this is a hard problem to solve.

Maybe mddox has to evaluate `<assembly-name>.deps.json` (contains package and project references) and `<assembly-name>.runtimeconfig.dev.json` (contains assembly probing paths) in order to find the referenced assemblies and then feed them to DocXml?

**Comment by bert2** [comment]
A much cheaper solution/workaround might be to catch such errors, ask the user to input the path to the assembly, load the specified assembly with `Assembly.LoadFrom()` and then try `TypeCollection.ForReferencedTypes()` again.

**Comment by loxsmoke** [comment]
Thank you for your investigation.

Finding all referenced DLLs from project files is challenging. This is the job of the compiler. I would really hate to re-implement and maintain such functionality in the simple command-line tool. 

The easiest workaround is to run `dotnet publish` instead of `dotnet build`. Publish copies necessary DLLs in one folder. Mddox (or rather .net CLR) then has not trouble finding assemblies.

**Comment by bert2** [comment]
Nice, thank you! That works for netcoreapp2.1 and netstandard2.0.

Do you have plans updating mddox to netcoreapp3.1?

**Comment by loxsmoke** [comment]
Try mddox 0.4.2-beta. It is netcoreapp3.1. Let me know if it works.

**Comment by bert2** [comment]
Yup upgrading worked. Found some unrelated problems with `ref`, `in`, and `out` types in DocXml though. I created a PR: https://github.com/loxsmoke/DocXml/pull/5

**Comment by loxsmoke** [comment]
Closing this issue.
